ALTER TABLE `users`
ADD `nickname` varchar(50) DEFAULT NULL,
ADD `title` varchar(30) DEFAULT NULL,
ADD `legal_name` varchar(30) DEFAULT NULL,
ADD `age_range` enum('less_than_18', '18_to_24', '25_to_34', '35_to_44', '45_to_54', '55_to_64', 'above_65') DEFAULT NULL,
ADD `read_preference` set('international', 'cross_straits', 'human_right', 'society', 'environment', 'education', 'politics', 'economy', 'culture', 'art', 'life', 'health', 'sport', 'all') DEFAULT NULL,
ADD `words_for_twreporter` varchar(255) DEFAULT NULL;

ALTER TABLE `pay_by_prime_donations`
ADD `receipt_security_id` varchar(20) DEFAULT NULL,
ADD `receipt_email` varchar(100) DEFAULT NULL,
ADD `receipt_address_country` varchar(45) DEFAULT NULL,
ADD `receipt_address_state` varchar(45) DEFAULT NULL,
ADD `receipt_address_city` varchar(45) DEFAULT NULL,
ADD `receipt_address_detail` varchar(255) DEFAULT NULL,
ADD `receipt_address_zip_code` varchar(10) DEFAULT NULL,
ADD `auto_tax_dedution` tinyint(1) DEFAULT NULL,
ADD `cardholder_last_name` varchar(30) DEFAULT NULL,
ADD `cardholder_first_name` varchar(30) DEFAULT NULL,
ADD `cardholder_security_id` varchar(20) DEFAULT NULL,
ADD `cardholder_gender` varchar(2) DEFAULT NULL,
ADD `cardholder_nickname` varchar(50) DEFAULT NULL,
ADD `cardholder_title` varchar(30) DEFAULT NULL,
ADD `cardholder_legal_name` varchar(30) DEFAULT NULL,
ADD `cardholder_address_country` varchar(45) DEFAULT NULL,
ADD `cardholder_address_state` varchar(45) DEFAULT NULL,
ADD `cardholder_address_city` varchar(45) DEFAULT NULL,
ADD `cardholder_address_detail` varchar(255) DEFAULT NULL,
ADD `cardholder_address_zip_code` varchar(10) DEFAULT NULL,
ADD `cardholder_age_range` enum('less_than_18', '18_to_24', '25_to_34', '35_to_44', '45_to_54', '55_to_64', 'above_65') DEFAULT NULL,
ADD `cardholder_read_preference` set('international', 'cross_straits', 'human_right', 'society', 'environment', 'education', 'politics', 'economy', 'culture', 'art', 'life', 'health', 'sport', 'all') DEFAULT NULL,
ADD `cardholder_words_for_twreporter` varchar(255) DEFAULT NULL;

ALTER TABLE `periodic_donations`
ADD `pay_method` enum('credit_card', 'line', 'apple', 'google', 'samsung') DEFAULT NULL,
ADD `receipt_security_id` varchar(20) DEFAULT NULL,
ADD `receipt_email` varchar(100) DEFAULT NULL,
ADD `receipt_address_country` varchar(45) DEFAULT NULL,
ADD `receipt_address_state` varchar(45) DEFAULT NULL,
ADD `receipt_address_city` varchar(45) DEFAULT NULL,
ADD `receipt_address_detail` varchar(255) DEFAULT NULL,
ADD `receipt_address_zip_code` varchar(10) DEFAULT NULL,
ADD `auto_tax_dedution` tinyint(1) DEFAULT NULL,
ADD `cardholder_last_name` varchar(30) DEFAULT NULL,
ADD `cardholder_first_name` varchar(30) DEFAULT NULL,
ADD `cardholder_security_id` varchar(20) DEFAULT NULL,
ADD `cardholder_gender` varchar(2) DEFAULT NULL,
ADD `cardholder_nickname` varchar(50) DEFAULT NULL,
ADD `cardholder_title` varchar(30) DEFAULT NULL,
ADD `cardholder_legal_name` varchar(30) DEFAULT NULL,
ADD `cardholder_address_country` varchar(45) DEFAULT NULL,
ADD `cardholder_address_state` varchar(45) DEFAULT NULL,
ADD `cardholder_address_city` varchar(45) DEFAULT NULL,
ADD `cardholder_address_detail` varchar(255) DEFAULT NULL,
ADD `cardholder_address_zip_code` varchar(10) DEFAULT NULL,
ADD `cardholder_age_range` enum('less_than_18', '18_to_24', '25_to_34', '35_to_44', '45_to_54', '55_to_64', 'above_65') DEFAULT NULL,
ADD `cardholder_read_preference` set('international', 'cross_straits', 'human_right', 'society', 'environment', 'education', 'politics', 'economy', 'culture', 'art', 'life', 'health', 'sport', 'all') DEFAULT NULL,
ADD `cardholder_words_for_twreporter` varchar(255) DEFAULT NULL;
