## Data Structures

### SigninRequest
+ email: user@example.com (required)
+ destination: https://www.twreporter.org
+ errorRedirection: https://www.twreporter.org

### SigninResponse
+ data (object, required) - The user data
    + email: example@email.com (string) - The user email

### UserData
+ data (object, required) - The user object
    + user_id: 123 (string) - The unique identifier of the user
    + email: example@email.com (string) - The email address of the user
    + name: Full Name (string) - The full name of the user
    + activated: true (boolean) - The activated status of the user (e.g. true / false)
    + read_preference (array) - Subscribed topics

# Group Membership Service
Twreporter Membership service api

## Signin [/v2/signin]
Validate the logining user and send the activation email

### User signins [POST]
+ Request with Body (application/json)

    + Attributes(SigninRequest)

+ Response 200 (application/json)

    + Attributes
        + status: success (required)
        + data (SigninRequest, required)

+ Response 201 (application/json)

    + Attributes
        + status: success (required)
        + data (SigninRequest, required)

+ Response 400

    + Attributes
        + status: fail (required)
        + data
            + email: "email is required"
            + destination: "destination is optional"

+ Response 500

    + Attributes
        + status: error (required)
        + message: "Generating active token occurs error"


## Authenticate [/v2/authenticate]
Validate the logining user and send the authentication email

### User authenticates [POST]
+ Request with Body (application/json)

    + Attributes(SigninRequest)

+ Response 200 (application/json)

    + Attributes
        + status: success (required)
        + data (SigninRequest, required)

+ Response 201 (application/json)

    + Attributes
        + status: success (required)
        + data (SigninRequest, required)

+ Response 400

    + Attributes
        + status: fail (required)
        + data
            + email: "email is required"
            + destination: "destination is optional"

+ Response 500

    + Attributes
        + status: error (required)
        + message: "Generating active token occurs error"

## Activate [/v2/activate{?email,token,destination}]
Send identity token if valid user sigins

### Activate user [GET]
+ Parameters
    + email: user@example.com (required)
    + token: 26dlFidiTVY= (required)
    + destination: https://www.twreporter.org (optional)

+ Response 302

    + Headers

            Set-Cookie: id_token=<cookie value>; Domain=twreporter.org; Max-Age=15552000; HttpOnly; Secure

## Token [/v2/token]
Authenticate user request and grant access token to the corresponding domain

### Dispatch access token [POST]
+ Request

    + Headers

            Cookie: id_token=<cookie value>

+ Response 200

    + Attributes
        + status: success (required)
        + data
            + jwt: access_token (required)

+ Response 401

    + Attributes
        + status: fail (required)
        + data
            + `req.Headers.Cookie.id_token`: id_token is invalid

+ Response 500

    + Attributes
        + status: error (required)
        + message: cannot get user data

## Logout [/v2/logout{?destination}]
Invalidate the identity token set on the root domain

### User logouts [GET]
+ Parameters
    + destination: https://www.twreporter.org

+ Response 302

## User Info [/v2/users/{id}]

### Get user [GET]

Get user related data (e.g. preferences, activation status, subscribed topics)

+ Parameters
    + id: 123 (string) - The unique identifier of the user

+ Request

    + Headers

            Content-Type: application/json
            Cookie: id_token=<id_token>
            Authorization: Bearer <jwt>

+ Response 200 (application/json)

    + Attributes
        + status: success (string, required) - The status of the API request (e.g. "success", "error")
        + data(UserData)

+ Response 400

    + Attributes
        + status: fail (required)
        + message: Bad Request - The request body is missing required parameters or contains invalid data

+ Response 401

    + Attributes
        + status: error (required)
        + message: Unauthorized - The access token is invalid or has expired

+ Response 500

    + Attributes
        + status: error (required)
        + message: Internal Server Error - An error occurred while processing the request

### Set user [POST]

Set user related data (e.g. preferences, subscribed topics and mail list subscriptions)

+ Parameters
    + id: 123 (string) - The unique identifier of the user

+ Request with Body

    + Headers

            Content-Type: application/json
            Cookie: id_token=<id_token>
            Authorization: Bearer <jwt>

    + Attributes
        + read_preference (array) - The topics the user is interesting in
        + maillist (array) - The mail list that user subscribed

+ Response 201 (application/json)

    + Attributes
        + status: success (string, required)

+ Response 400

    + Attributes
        + status: fail (required)
        + message: Bad Request - The request body is missing required parameters or contains invalid data

+ Response 401

    + Attributes
        + status: error (required)
        + message: Unauthorized - The access token is invalid or has expired

+ Response 500

    + Attributes
        + status: error (required)
        + message: Internal Server Error - An error occurred while processing the request

## 6-digit OTP Logins [/v3/signin]
Validate the logining user and send the signin email with 6-digit code

### SignInV3 [POST]

+ Request with Body (application/json)

    + Attributes
        + email (string, required) - The email of the user

+ Response 200 (application/json)

    + Attributes
        + status: success (string, required)
        + data(SigninResponse)

+ Response 400

    + Attributes
        + status: fail (required)
        + message: Bad Request - The request body is missing required parameters or contains invalid data

+ Response 500

    + Attributes
        + status: error (required)
        + message: Internal Server Error - An error occurred while processing the request

## 6-digit OTP Logins [/v3/activate]
Verify the logining user with email and 6-digit code

### ActivateV3 [POST]

+ Request with Body (application/json)

    + Attributes
        + email (string, required) - The email of the user
        + code (string, required) - The 6-digit code in the signin mail

+ Response 200 (application/json)

    + Attributes
        + status: success (string, required)
        + data(SigninResponse)

+ Response 400

    + Attributes
        + status: fail (required)
        + message: Bad Request - The request body is missing required parameters or contains invalid data

+ Response 500

    + Attributes
        + status: error (required)
        + message: Internal Server Error - An error occurred while processing the request
