# Group Tappay Synchronization

## Tappay Record [/v1/tappay_query]

### Post to get a tappay record[POST]
Post to get a tappay record

+ Request

    + Attributes (TappayServerRequest)

    + Headers

            Content-Type: application/json
            Cookie: id_token=<id_token>
            Authorization: Bearer <jwt>
 
+ Response 200

    + Attributes 
        + status: Success (required)
        + data (TappayServerResponse) (required)

+ Response 401 (application/json)

    + Attributes (Error401Response)

+ Response 403 (application/json)

    + Attributes (Error403Response)
 
+ Response 404 (application/json)

    + Body

            {
                "status": "fail",
                "data": {
                    "filters": "{\"order_number\": \"twreporter-123\"} cannot address a existing resource."
                }
            }
   
+ Response 500
    
    + Attributes (Error500Response)
       
## Data Structures
### TappayServerRequest
+ records_per_page: 1 (optional, number)
+ filters
    + `order_number`: `twreporter-153371414230837160610` (required)
    + `rec_trade_id`: LN201711088cHQHr (optional)
    + `bank_transaction_id`: TP201711088cHQHr (optional)

### TappayTradeRecords
+ record_status: 0 (number)

### TappayServerResponse
+ status: 0 (required, number)
+ msg: "" (required)
+ trade_records (array[TappayTradeRecords])
