# Group Email Service
Email service of TWreporter Go API

## Thank-You Donation Email [/v1/mail/send_success_donation]
Send thank-you donation email to a user.
The email contains the following attributes
- address - address of the user
- amount - donation amount
- card_info_four_number - last four number of credit card, e.g. 4242
- card_info_type - type of credit card, e.g. VISA
- currency - donation currency, e.g. TWD
- donation_datetime - datetime(YYYY-MM-DD hh:mm:ss) of donation made, e.g. 2018-10-30 14:00:01
- donation_link - URL of the web page of the donation
- donation_method - the way user pay the money, e.g. 信用卡支付
- donation_type - donation type, e.g. 定期定額
- email - email of the user
- name - name of the user
- national_id - national id of the user
- order_number - donation order number
- phone_number - phone number of the user

### Send a Thank-You Donation Email to a User [POST]
+ Request 

    + Headers

            Content-Type: application/json
            Authorization: Bearer <jwt>
            
    + Attributes (DonationSuccessMailModel)

+ Response 204

+ Response 400 (application/json)

    + Body

            {
                "status": "fail",
                "data": {
                    "address": "address is optional"
                    "amount": "amount(number) is required",
                    "card_info_four_number": "card_info_four_number is optional",
                    "card_info_type": "card_info_type is optional",
                    "currency": "currency is optional, default is TWD",
                    "donation_datetime": "donation_datetime is optional, default is current datetime",
                    "donation_link": "donation_link is optional",
                    "donation_method": "donation_method is required",
                    "donation_type": "donation_type is required",
                    "email": "email is required",
                    "name": "name is optional",
                    "national_id": "national_id is optional",
                    "order_number": "order_number is required",
                    "phone_number: "phone_number is optional"
                }
            }

+ Response 401 (application/json)

    + Body

            {
                "status": "fail",
                "data": {
                    "req.Headers.Authorization": "JWT is not valid"
                }
            }

+ Response 500 (application/json)

    
    + Body

            {
                "status": "error",
                "message": "unknown error."
            }


## Data Structures
### DonationSuccessMailModel
+ address: 台北市南京東路一段100號
+ amount: 500 (required, number)
+ `card_info_four_number`: 4242
+ `card_info_type`: visa
+ currency: TWD
+ `donation_datetime`: `2018-10-30 12:45:30`
+ `donation_link`: `https://support.twreporter.org/`
+ `donation_method`: 信用卡支付 (required)
+ `donation_type`: 定期定額 (required)
+ email: developer@twreporter.org (required)
+ name: 王小明
+ `national_id`: A12345678
+ `order_number`: `twreporter-154081514233102449410` (required)
+ `phone_number`: 0225602020
