# Group Periodic Donation
Periodic donation resources of go-api

## Periodic Donation [/v1/periodic-donations/{id}{?user_id}]
A single Periodic Donation.
The Periodic Donation is the resource in the TWReporter Donation API. 
It reprensents one periodic donation record.

The Periodic Donation resource has the following attributes;
- id
- amount
- card_info
- card_info.bind_code
- card_info.country
- card_info.country_code
- card_info.expiry_date
- card_info.funding
- card_info.issuer
- card_info.last_four
- card_info.level
- card_info.type
- cardholder
- cardholder.address
- cardholder.email
- cardholder.name
- cardholder.national_id
- cardholder.phone_number
- cardholder.zip_code
- currency
- details
- frequency
- notes
- order_number
- send_receipt
- to_feedback
- max_paid_times

The states *id* and *order_number* are assigned by the TWReporter Go API at the moment of creation.

### Retrieve a Single Periodic Donation [GET]
+ Parameters
    + id (number) ... ID of the Periodic Donation
    + user_id (number) ... ID of the user

+ Request

    + Headers 

              Authorization: Bearer <jwt>

+ Response 200

    + Attributes (PeriodicDonationResponse)
        

+ Response 401 (application/json)

    + Body

            {
                "status": "fail",
                "data": {
                    "req.Headers.Authorization": "JWT is not valid"
                }
            }

+ Response 403 (application/json)

    + Body

            {
                "status": "fail",
                "data": {
                    "req.Headers.Authorization": "request is not permitted for the resource"
                }
            }

+ Response 404 (application/json)

    + Body

            {
                "status": "fail",
                "data": {
                    "req.URL": "url can not address a resource"
                }
            }

+ Response 500 (application/json)

    
    + Body

            {
                "status": "error",
                "message": "unknown error."
            }


### Modify a Single Periodic Donation [PATCH]
+ Parameters
    + id (number) ... ID of the Periodic Donation

+ Request 

    + Headers

            Content-Type: application/json
            Authorization: Bearer <jwt>
            
    + Attributes (object)
        + donor (object)
            + address: 台北市南京東路一段300巷300號6樓
            + email: developer@twreporter.org
            + name: 王小明
            + phone_number: +886912345678
            + national_id: A12345678
        + notes: 第一次捐款報導者喔
        + send_receipt: yearly
        + to_feedback: false
        + user_id: 1 (required)

+ Response 204

+ Response 400 (application/json)

    + Body

            {
                "status": "fail",
                "data": {
                    "donor": {
                        "email": "email(string) is optional",
                        "address": "address(string) is optional",
                        "name": "name(string) is optional",
                        "zip_code": "zip_code(string) is optional",
                        "phone_number": "phone_number(string) is optional",
                        "national_id": "national_id(string) is optional"
                    },
                    "notes": "notes(string) is optional",
                    "send_receipt": "send_receipt(string) is optional. only support 'no', 'monthly' and 'yearly'",
                    "to_feedback": "to_feedback(bool) is optional."
                    "user_id": "user_id(number) is required"
                }
            }

+ Response 401 (application/json)

    + Body

            {
                "status": "fail",
                "data": {
                    "req.Headers.Authorization": "JWT is not valid"
                }
            }

+ Response 403 (application/json)

    + Body

            {
                "status": "fail",
                "data": {
                    "req.Headers.Authorization": "request is not permitted for the resource"
                }
            }

+ Response 500 (application/json)

    
    + Body

            {
                "status": "error",
                "message": "unknown error."
            }

## Periodic Donation [/v1/periodic_donations]

### Create a Single Periodic Donation [POST]

+ Request 

    + Headers

            Content-Type: application/json
            Authorization: Bearer <jwt>
            
    + Attributes (object)
        + amount: 500 (required, number)
        + currency: TWD 
        + details: 報導者定期定額捐款
        + donor (required, object)
            + email: developer@twporter.org (required)
        + frequency: monthly (required)
        + prime: `test_3a2fb2b7e892b914a03c95dd4dd5dc7970c908df67a49527c0a648b2bc9` (required)
        + `merchant_id`: `twreporter_CTBC`
        + `user_id`: 1 (required, number)
        + `max_paid_times`: 3 (optional, number)

+ Response 201

    + Attributes (PeriodicDonationResponse)

+ Response 400 (application/json)

    + Body

            {
                "status": "fail",
                "data": {
                    "prime": "prime(string) is required",
                    "amount": "amount(number) is required",
                    "donor": {
                        "email": "email(string) is required",
                    },
                    "details": "details(string) is optional",
                    "merchant_id": "merchant_id(string) is optional",
                    "frequency": "frequency(string) is optional, default: 'monthly'. only support 'monthly' and 'yearly'",
                    "user_id": "user_id(number) is required",
                    "max_paid_times": "max_paid_times(number) is optional, default: 2147483647"
                }
            }

+ Response 401 (application/json)

    + Body

            {
                "status": "fail",
                "data": {
                    "req.Headers.Authorization": "JWT is not valid"
                }
            }

+ Response 403 (application/json)

    + Body

            {
                "status": "fail",
                "data": {
                    "req.Headers.Authorization": "request is not permitted for the resource"
                }
            }

+ Response 500 (application/json)

    
    + Body

            {
                "status": "error",
                "message": "unknown error."
            }

## Data Structures

### PeriodicDonationModel
+ id: 1 (required, number)
+ amount: 500 (required, number)
+ currency: TWD (required)
+ details: 報導者定期定額捐款 (required)
+ frequency: monthly (required)
+ notes: 第一次捐給報導者喔 (optional)
+ `order_number`: `twreporter-153985253506653918900` (required)
+ `send_receipt`: monthly (required)
+ `to_feedback`: true (required, boolean)
+ `cardholder` (required)
    + email: developer@twreporter.org (required)
    + name: 王小明 (optional)
    + address: 台北市南京東路一段300巷300號6樓 (optional)
    + phone_number: +886912345678 (optional)
    + `national_id`: A12345678 (optional)
    + `zip_code`: 104 (optional)
+ `card_info` (required)
    + `bin_code`: 424242 (required)
    + country: UNITED KINGDOM" (required)
    + `country_code`: GB (required)
    + `expiry_date`: 201810 (required)
    + funding: 0 (required, number)
    + issuer: JPMORGAN CHASE BANK NA (required)
    + type: 1 (required, number)
    + level: card_level (required)

### PeriodicDonationResponse
+ status: sucess (required)
+ data (PeriodicDonationModel)
