# Group Prime Donation
Prime donation resources of go-api

## Prime Donation [/v1/donations/prime/orders/{order}]
A single Prime Donation.
The Prime Donation is the resource in the TWReporter Donation API. 
It reprensents one prime donation record identified by the order number (order).

The Prime Donation resource has the following attributes;
- id
- amount
- card_info
- card_info.bind_code
- card_info.country
- card_info.country_code
- card_info.expiry_date
- card_info.funding
- card_info.issuer
- card_info.last_four
- card_info.level
- card_info.type
- cardholder
- cardholder.address
- cardholder.email
- cardholder.name
- cardholder.national_id
- cardholder.phone_number
- cardholder.zip_code
- currency
- details
- frequency
- notes
- order_number
- pay_method
- send_receipt
- is_anonymous

The states *id* and *order_number* are assigned by the TWReporter Go API at the moment of creation.

### Retrieve a Single Prime Donation [GET]
+ Parameters
    + order (string) ... an order number of the Prime Donation

+ Request

    + Headers 

              Cookie: id_token=<id_token>
              Authorization: Bearer <jwt>

+ Response 200

    + Attributes (PrimeDonationCommon)
        
+ Response 401 (application/json)

    + Attributes (Error401Response)

+ Response 403 (application/json)

    + Attributes (Error403Response)
    
+ Response 404 (application/json)

    + Body

            {
                "status": "fail",
                "data": {
                    "req.URL": "url can not address a resource"
                }
            }

+ Response 500 (application/json)

    + Attributes (Error500Response)

### Modify a Single Prime Donation [PATCH]
+ Parameters
    + order (string) ... an order number of the Prime Donation

+ Request 

    + Headers

            Content-Type: application/json
            Cookie: id_token=<id_token>
            Authorization: Bearer <jwt>
            
    + Attributes (object)
        + donor (object)
            + address: 台北市南京東路一段300巷300號6樓
            + email: developer@twreporter.org
            + name: 王小明
            + phone_number: +886912345678
            + national_id: A12345678
        + notes: 第一次捐款報導者喔
        + send_receipt: no
        + is_anonymous: true
        + user_id: 1 (required)

+ Response 204

+ Response 400 (application/json)

    + Body

            {
                "status": "fail",
                "data": {
                    "donor": {
                        "email": "email(string) is optional",
                        "address": "address(string) is optional",
                        "name": "name(string) is optional",
                        "zip_code": "zip_code(string) is optional",
                        "phone_number": "phone_number(string) is optional",
                        "national_id": "national_id(string) is optional"
                    },
                    "notes": "notes(string) is optional",
                    "send_receipt": "send_receipt(string) is optional. only support 'no', 'monthly' and 'yearly'",
                    "is_anonymous": "is_anonymous(bool) is optional."
                    "user_id": "user_id(number) is required"
                }
            }

+ Response 401 (application/json)

    + Body

            {
                "status": "fail",
                "data": {
                    "req.Headers.Authorization": "JWT is not valid"
                }
            }

+ Response 403 (application/json)

    + Body

            {
                "status": "fail",
                "data": {
                    "req.Headers.Authorization": "request is not permitted for the resource"
                }
            }

+ Response 500 (application/json)

    
    + Body

            {
                "status": "error",
                "message": "unknown error."
            }

## Prime Donation [/v1/donations/prime]

### Create a Single Prime Donation [POST]

+ Request Credit Card

    + Headers

            Content-Type: application/merge-patch+json
            Cookie: id_token=<id_token>
            Authorization: Bearer <jwt>
            
    + Attributes (object)
        + amount: 500 (required, number)
        + currency: TWD 
        + details: 報導者單筆捐款
        + donor (required, object)
            + email: developer@twporter.org (required)
        + prime: `test_3a2fb2b7e892b914a03c95dd4dd5dc7970c908df67a49527c0a648b2bc9` (required)
        + `pay_method`: `credit_card` (required)
        + `merchant_id`: `twreporter_CTBC`
        + `user_id`: 1 (required, number)

+ Response 201

    + Attributes (PrimeDonationByCreditCardResponse)

+ Response 400 (application/json)

    + Attributes (Error400CreatePrimeResponse)

+ Response 401 (application/json)

    + Attributes (Error401Response)

+ Response 403 (application/json)

    + Attributes (Error403Response)
 
+ Response 500 (application/json)

    + Attributes (Error500Response)

+ Request Line Pay

    + Headers

            Content-Type: application/merge-patch+json
            Cookie: id_token=<id_token>
            Authorization: Bearer <jwt>
            
    + Attributes (object)
        + amount: 500 (required, number)
        + currency: TWD 
        + details: 報導者單筆捐款
        + donor (required, object)
            + email: developer@twporter.org (required)
        + prime: `test_3a2fb2b7e892b914a03c95dd4dd5dc7970c908df67a49527c0a648b2bc9` (required)
        + `pay_method`: `line` (required)
        + `merchant_id`: `TW_LINE_PAY`
        + `user_id`: 1 (required, number)

+ Response 201

    + Attributes (PrimeDonationByLinePayResponse)

+ Response 400 (application/json)

    + Attributes (Error400CreatePrimeResponse)

+ Response 401 (application/json)

    + Attributes (Error401Response)

+ Response 403 (application/json)

    + Attributes (Error403Response)
    
+ Response 500 (application/json)

    + Attributes (Error500Response)

## Line Pay Backend Notification [/v1/donations/prime/line-notify]
Endpoint for tappay server to notify line pay transaction result
### Notify Line Transaction Endpoint [POST]

+ Request with body (application/json)

    + Attributes (TapPayLinePayNotification)

+ Response 204

+ Response 400 (application/json)

+ Response 422 (application/json)

## Data Structures
### PrimeDonationCommon
+ id: 1 (required, number)
+ amount: 500 (required, number)
+ currency: TWD (required)
+ details: 報導者單筆捐款 (required)
+ notes: 第一次捐給報導者喔 (optional)
+ `order_number`: `twreporter-153985253506653918900` (required)
+ `send_receipt`: monthly (required)
+ `pay_method`: `credit_card` (required)
+ `is_anonymous`: false (required, boolean)
+ `cardholder` (required)
    + email: developer@twreporter.org (required)
    + name: 王小明 (optional)
    + address: 台北市南京東路一段300巷300號6樓 (optional)
    + phone_number: +886912345678 (optional)
    + `national_id`: A12345678 (optional)
    + `zip_code`: 104 (optional)

### PrimeDonationByCreditCardResponse
+ status: success (required)
+ data (PrimeDonationCommon) 
    
### PrimeDonationByLinePayResponse
+ status: success (required)
+ data 
    + Include PrimeDonationCommon
    + payment_url: `https://sandbox-redirect.tappaysdk.com/redirect/906ec8348e5e893e098e56f1c061ae178fc80d193649305e83ca8788054e839d`

### Error400CreatePrimeResponse
+ status: fail
+ data
    + prime: `prime(string) is required`
    + amount: `amount(number) is required`
    + donor 
        + email: `email(string) is required`
    + details: `details(string) is optional`
    + `merchant_id`: `merchant_id(string) is optional`
    + `pay_method`: `pay_method(string) is required, currently only support credit_card and line`
    + `user_id`: `user_id(number) is required`
    
### Error401Response
+ status: fail
+ data
    + `req.Headers.Authorization`: JWT is not valid

### Error403Response
+ status: fail
+ data
    + `req.Headers.Authorization`: request is not permitted for the resource

### Error500Response
+ status: error
+ message: unknown error

### TapPayLinePayNotification
+ `rec_trade_id`: LN201711088cHQHr (required)
+ `bank_transaction_id`: TP201711088cHQHr (required)
+ `order_number`: twreporter-153985253506653918901 (required)
+ amount: 500 (required, number)
+ status: 0 (required, number)
+ msg: Success (required)
+ `transaction_time_millis`: 1510136365539 (required, number)
+ `pay_info` (required)
    + method: CREDIT_CARD
    + masked_credit_card_number: ************4242
    + point: 0 (optional, number)
+ acquirer: TW_LINE_PAY (required)
+ `bank_result_code`: 0 (optional, number)
+ `bank_result_msg` (string, nullable)

