# Group Prime Donation
Prime donation resources of go-api

## Prime Donation [/v1/donations/prime/orders/{order}]
A single Prime Donation.
The Prime Donation is the resource in the TWReporter Donation API. 
It represents one prime donation record identified by the order number (order).

The Prime Donation resource has the following attributes:
- id
- amount
- card_info
- card_info.bind_code
- card_info.country
- card_info.country_code
- card_info.expiry_date
- card_info.funding
- card_info.issuer
- card_info.last_four
- card_info.level
- card_info.type
- cardholder
- cardholder.address_country
- cardholder.address_state
- cardholder.address_city
- cardholder.address_detail
- cardholder.address_zip_code
- cardholder.email
- cardholder.first_name
- cardholder.last_name
- cardholder.security_id
- cardholder.phone_number
- cardholder.zip_code
- cardholder.nickname
- cardholder.title
- cardholder.legal_name
- cardholder.gender
- cardholder.age_range
- cardholder.read_preference
- cardholder.words_for_twreporter
- currency
- details
- frequency
- order_number
- pay_method
- send_receipt
- is_anonymous
- receipt 
- receipt.header
- receipt.security_id
- receipt.email
- receipt.address_country
- receipt.address_state
- receipt.address_city
- receipt.address_detail
- receipt.address_zip_code
- auto_tax_dedution

The states *id* and *order_number* are assigned by the TWReporter Go API at the moment of creation.

### Retrieve a Single Prime Donation [GET]
+ Parameters
    + order (string) ... an order number of the Prime Donation

+ Request

    + Headers 

              Cookie: id_token=<id_token>
              Authorization: Bearer <jwt>

+ Response 200

    + Attributes (PrimeDonationCommon)
        
+ Response 401 (application/json)

    + Attributes (Error401Response)

+ Response 403 (application/json)

    + Attributes (Error403Response)
    
+ Response 404 (application/json)

    + Body

            {
                "status": "fail",
                "data": {
                    "req.URL": "url can not address a resource"
                }
            }

+ Response 500 (application/json)

    + Attributes (Error500Response)

### Modify a Single Prime Donation [PATCH]
+ Parameters
    + order (string) ... an order number of the Prime Donation

+ Request 

    + Headers

            Content-Type: application/json
            Cookie: id_token=<id_token>
            Authorization: Bearer <jwt>
            
    + Attributes (object)
        + donor (object)
            + address_country: 臺灣
            + address_state: 臺北市
            + address_city: 中山區
            + address_detail: 南京東路一段300巷300號6樓
            + address_zip_code: 104
            + email: developer@twreporter.org
            + first_name: 小明 
            + last_name: 王
            + phone_number: +886912345678
            + security_id: A12345678
            + nickname: 小明
            + title: 工程師
            + legal_name: 報導者文化基金會
            + gender: M  
            + age_range: 25_to_34  
            + read_preference: human_right,cross_straits 
            + words_for_twreporter: 加油！  
        + send_receipt: no_receipt
        + is_anonymous: true
        + user_id: 1 (required)
        + receipt (object)
            + header: 王小明
            + security_id: A12345678
            + email: developer@twreporter.org
            + address_country: 臺灣
            + address_state: 臺北市
            + address_city: 中山區 
            + address_detail: 南京東路一段300巷300號6樓 
            + address_zip_code: 104 
        + auto_tax_dedution: true

+ Response 204

+ Response 400 (application/json)

    + Body

            {
                "status": "fail",
                "data": {
                    "donor": {
                        "email": "email(string) is optional",
                        "address_country": "address_country(string) is optional",
                        "address_state": "address_state(string) is optional",
                        "address_city": "address_city(string) is optional",
                        "address_detail": "address_detail(string) is optional",
                        "address_zip_code": "address_zip_code(string) is optional",
                        "first_name": "first_name(string) is optional",
                        "last_name": "last_name(string) is optional",
                        "phone_number": "phone_number(string) is optional",
                        "security_id": "security_id(string) is optional"
                        "nickname": "nickname(string) is optional",
                        "title": "title(string) is optional",
                        "legal_name": "legal_name(string) is optional",
                        "gender": "gender(string) is optional. only support 'F', 'M', 'X', 'U'",
                        "age_range": "age_range(string) is optional",
                        "read_preference": "read_preference(string) is optional",
                        "words_for_twreporter": "words_for_twreporter(string) is optional",
                    },
                    "send_receipt": "send_receipt(string) is optional. only support 'no_receipt', 'digital_receipt_by_month' and 'digital_receipt_by_year', 'paperback_receipt_by_month', 'paperback_receipt_by_year'",
                    "is_anonymous": "is_anonymous(bool) is optional.",
                    "user_id": "user_id(number) is required",
                    "receipt": {
                        "header": "header(string) is optional",
                        "security_id": "security_id(string) is optional",
                        "email": "email(string) is optional",
                        "address_country": "address_country(string) is optional",
                        "address_state": "address_state(string) is optional",
                        "address_city": "address_city(string) is optional",
                        "address_detail": "address_detail(string) is optional",
                        "address_zip_code": "address_zip_code(string) is optional",
                    },
                    "auto_tax_dedution": "auto_tax_dedution(bool) is optional",
                }
            }

+ Response 401 (application/json)

    + Body

            {
                "status": "fail",
                "data": {
                    "req.Headers.Authorization": "JWT is not valid"
                }
            }

+ Response 403 (application/json)

    + Body

            {
                "status": "fail",
                "data": {
                    "req.Headers.Authorization": "request is not permitted for the resource"
                }
            }

+ Response 500 (application/json)

    
    + Body

            {
                "status": "error",
                "message": "unknown error."
            }

## Transaction Verification Information [/v1/donations/prime/orders/{order}/transaction_verification]
Endpoint for frontend server to retrieve information for transaction verification.
Only the linepay is required to do this verfication
### Retrieve verification information of an order [GET]
+ Parameters
    + order (string) ... an order number of the Prime Donation

+ Request

    + Headers 

              Cookie: id_token=<id_token>
              Authorization: Bearer <jwt>

+ Response 200

    + Attributes (VerificationInformation)
        
+ Response 401 (application/json)

    + Attributes (Error401Response)

+ Response 403 (application/json)

    + Attributes (Error403Response)
    
+ Response 404 (application/json)

    + Body

            {
                "status": "fail",
                "data": {
                    "req.URL": "url can not address a resource"
                }
            }

+ Response 500 (application/json)

    + Attributes (Error500Response)

## Prime Donation [/v1/donations/prime]

### Create a Single Prime Donation [POST]

+ Request Credit Card

    + Headers

            Content-Type: application/merge-patch+json
            Cookie: id_token=<id_token>
            Authorization: Bearer <jwt>
            
    + Attributes (object)
        + amount: 500 (required, number)
        + currency: TWD 
        + details: 報導者單筆捐款
        + donor (required, object)
            + email: developer@twporter.org (required)
        + prime: `test_3a2fb2b7e892b914a03c95dd4dd5dc7970c908df67a49527c0a648b2bc9` (required)
        + `pay_method`: `credit_card` (required)
        + `merchant_id`: `twreporter_CTBC`
        + `user_id`: 1 (required, number)

+ Response 201

    + Attributes (PrimeDonationByCreditCardResponse)

+ Response 400 (application/json)

    + Attributes (Error400CreatePrimeResponse)

+ Response 401 (application/json)

    + Attributes (Error401Response)

+ Response 403 (application/json)

    + Attributes (Error403Response)
 
+ Response 500 (application/json)

    + Attributes (Error500Response)

+ Request Line Pay

    + Headers

            Content-Type: application/merge-patch+json
            Cookie: id_token=<id_token>
            Authorization: Bearer <jwt>
            
    + Attributes (object)
        + amount: 500 (required, number)
        + currency: TWD 
        + details: 報導者單筆捐款
        + donor (required, object)
            + email: developer@twporter.org (required)
        + prime: `test_3a2fb2b7e892b914a03c95dd4dd5dc7970c908df67a49527c0a648b2bc9` (required)
        + `pay_method`: `line` (required)
        + `merchant_id`: `TW_LINE_PAY`
        + `user_id`: 1 (required, number)

+ Response 201

    + Attributes (PrimeDonationByLinePayResponse)

+ Response 400 (application/json)

    + Attributes (Error400CreatePrimeResponse)

+ Response 401 (application/json)

    + Attributes (Error401Response)

+ Response 403 (application/json)

    + Attributes (Error403Response)
    
+ Response 500 (application/json)

    + Attributes (Error500Response)

## Line Pay Backend Notification [/v1/donations/prime/line-notify]
Endpoint for tappay server to notify line pay transaction result
### Notify Line Transaction Endpoint [POST]

+ Request with body (application/json)

    + Attributes (TapPayLinePayNotification)

+ Response 200

+ Response 400 (application/json)

+ Response 422 (application/json)

## Data Structures
### PrimeDonationCommon
+ id: 1 (required, number)
+ amount: 500 (required, number)
+ currency: TWD (required)
+ details: 報導者單筆捐款 (required)
+ `order_number`: `twreporter-153985253506653918900` (required)
+ `send_receipt`: no_receipt (required)
+ `pay_method`: `credit_card` (required)
+ `is_anonymous`: false (required, boolean)
+ `cardholder` (required)
    + email: developer@twreporter.org (required)
    + first_name: 小明 (optional)
    + last_name: 王 (optional)
    + phone_number: +886912345678 (optional)
    + `security_id`: A12345678 (optional)
    + address_country: 臺灣 (optional)
    + address_state: 臺北市 (optional)
    + address_city: 中山區 (optional)
    + address_detail: 南京東路一段300巷300號6樓 (optional)
    + address_zip_code: 104 (optional)
    + nickname: 小明 (optional)
    + title: 工程師 (optional)
    + legal_name: 報導者文化基金會 (optional)
    + gender: M (optional)  
    + age_range: 25_to_34 (optional) 
    + read_preference: human_right,cross_straits (optional)
    + words_for_twreporter: 加油！(optional)  
+ receipt (optional)
    + header: 王小明 (optional)
    + security_id: A12345678 (optional)
    + email: developer@twreporter.org (optional)
    + address_country: 臺灣 (optional)
    + address_state: 臺北市 (optional)
    + address_city: 中山區 (optional)
    + address_detail: 南京東路一段300巷300號6樓 (optional)
    + address_zip_code: 104 (optional)
+ auto_tax_dedution: true (optional)

### PrimeDonationByCreditCardResponse
+ status: success (required)
+ data (PrimeDonationCommon) 
    
### PrimeDonationByLinePayResponse
+ status: success (required)
+ data 
    + Include PrimeDonationCommon
    + payment_url: `https://sandbox-redirect.tappaysdk.com/redirect/906ec8348e5e893e098e56f1c061ae178fc80d193649305e83ca8788054e839d`

### Error400CreatePrimeResponse
+ status: fail
+ data
    + prime: `prime(string) is required`
    + amount: `amount(number) is required`
    + donor 
        + email: `email(string) is required`
    + details: `details(string) is optional`
    + `merchant_id`: `merchant_id(string) is optional`
    + `pay_method`: `pay_method(string) is required, currently only support credit_card and line`
    + `user_id`: `user_id(number) is required`
    
### Error401Response
+ status: fail
+ data
    + `req.Headers.Authorization`: JWT is not valid

### Error403Response
+ status: fail
+ data
    + `req.Headers.Authorization`: request is not permitted for the resource

### Error500Response
+ status: error
+ message: unknown error

### TapPayLinePayNotification
+ `rec_trade_id`: LN201711088cHQHr (required)
+ `bank_transaction_id`: TP201711088cHQHr (required)
+ `order_number`: twreporter-153985253506653918901 (required)
+ amount: 500 (required, number)
+ status: 0 (required, number)
+ msg: Success (required)
+ `transaction_time_millis`: 1510136365539 (required, number)
+ `pay_info` (required)
    + method: CREDIT_CARD
    + masked_credit_card_number: ************4242
    + point: 0 (optional, number)
+ acquirer: TW_LINE_PAY (required)
+ `bank_result_code`: 0 (optional, number)
+ `bank_result_msg` (string, nullable)

### VerificationInformation
+ `rec_trade_id`: LN201711088cHQHr (required)
+ `bank_transaction_id`: TP201711088cHQHr (required)
+ status: paying
