## Data Structures

### UserData
+ user_id: 123 (string) - The unique identifier of the user
+ email: example@email.com (string) - The email address of the user
+ fisrt_name: First Name (string) - The first name of the user
+ last_name: Last Name (string) - The last name of the user
+ roles (array) - The role that has max weight value & not expired
    + (object)
        + id: 1 (string) - The unique identifier of the role.
        + name: 探索者 (string) - The name of the role in the local language.
        + name_en: explorer (string) - The name of the role in English.
        + key: explorer (string) - The key of the role.
    + (object)
        + id: 2 (string) - The unique identifier of the role.
        + name: 行動者 (string) - The name of the role in the local language.
        + name_en: action taker (string) - The name of the role in English.
        + key: action_taker (string) - The key of the role.
    + (object)
        + id: 3 (string) - The unique identifier of the role.
        + name: 開創者 (string) - The name of the role in the local language.
        + name_en: trailblazer (string) - The name of the role in English.
        + key: trailblazer (string) - The key of the role.
+ registration_date: `2018-01-24T22:16:48Z` (string) - The registration date of the user
+ activated: `2023-06-01T01:23:45Z` (string) - The activated status of the user. If the user is not activated, the value is null.
+ read_preference (array) - Subscribed topics
+ maillist (array) - Subscribed mail list
+ agree_data_collection: true (boolean) - True if user agree analytics data collection
+ read_posts_count: 19 (number) - Total count of user reading posts
+ read_posts_sec: 3360 (number) - Total time of user reading posts; digit is second.

### UserAnalytics
+ user_id: 123 (string) - The unique identifier of the user
+ post_id: 3844e928 (string) - The unique identifier of the post
+ read_posts_count: 19 (number) - Total count of user reading posts
+ read_posts_sec: 3360 (number) - Total time of user reading posts; digit is second.

### UserReadingFootprint
+ id: 5edf118c3e631f0600198935 (required)
+ slug: `a-slug-of-the-post` (required)
+ hero_image  (image, required)
+ title: post title (required)
+ subtitle: post subtitle (required)
+ description: post description (required)
+ category_set (array[category_set], fixed-type, required)
+ published_date: `2020-06-8T16:00:00Z` (required)
+ is_external: false (boolean, required)
+ bookmark_id: `119`
+ footprint_updated_at: `2020-06-8T16:00:00Z` (required)


# Group User Service
Twreporter User service api

## User Info [/v2/users/{id}]

### Get user [GET]

Get user related data (e.g. preferences, activation status, subscribed topics)

+ Parameters
    + id: 123 (string) - The unique identifier of the user

+ Request

    + Headers

            Content-Type: application/json
            Cookie: id_token=<id_token>
            Authorization: Bearer <jwt>

+ Response 200 (application/json)

    + Attributes
        + status: success (string, required) - The status of the API request (e.g. "success", "error")
        + data(UserData, required)

+ Response 400

    + Attributes
        + status: fail (required)
        + message: Bad Request - The request body is missing required parameters or contains invalid data

+ Response 401

    + Attributes
        + status: error (required)
        + message: Unauthorized - The access token is invalid or has expired

+ Response 500

    + Attributes
        + status: error (required)
        + message: Internal Server Error - An error occurred while processing the request

### Set user [POST]

Set user related data (e.g. preferences, subscribed topics and mail list subscriptions)

+ Parameters
    + id: 123 (string) - The unique identifier of the user

+ Request with Body

    + Headers

            Content-Type: application/json
            Cookie: id_token=<id_token>
            Authorization: Bearer <jwt>

    + Attributes
        + read_preference (array) - The topics the user is interesting in
            + international
            + cross_straits
            + human_right
            + society
            + environment
            + education
            + politics
            + economy
            + culture
            + art
            + life
            + health
            + sport
            + all
        + maillist (array) - The mail list that user subscribed
            + featured
            + behind_the_scenes
            + operational_journal

+ Response 201 (application/json)

    + Attributes
        + status: success (string, required)

+ Response 400

    + Attributes
        + status: fail (required)
        + message: Bad Request - The request body is missing required parameters or contains invalid data

+ Response 401

    + Attributes
        + status: error (required)
        + message: Unauthorized - The access token is invalid or has expired

+ Response 500

    + Attributes
        + status: error (required)
        + message: Internal Server Error - An error occurred while processing the request

## User Analytics [/v2/users/{id}/analytics]

### Update user analytics [POST]

Add user analytics data

+ Parameters
    + id: 123 (string) - The unique identifier of the user

+ Request with Body

    + Headers

            Content-Type: application/json
            Cookie: id_token=<id_token>
            Authorization: Bearer <jwt>

    + Attributes
        + post_id (string, required) - The post id of recording user reading analytics data
        + read_posts_count (boolean) - True if user read this post
        + read_posts_sec (number) - Time user spend reading this post

+ Response 200 (application/json)

    + Attributes
        + status: success (string, required)
        + data(UserAnalytics, required)

+ Response 201 (application/json)

    + Attributes
        + status: success (string, required)
        + data(UserAnalytics, required)

+ Response 400

    + Attributes
        + status: fail (required)
        + message: Bad Request - The request body is missing required parameters or contains invalid data

+ Response 401

    + Attributes
        + status: error (required)
        + message: Unauthorized - The access token is invalid or has expired

+ Response 500

    + Attributes
        + status: error (required)
        + message: Internal Server Error - An error occurred while processing the request

## User Analytics Of Reading Footprint [/v2/users/{id}/analytics/reading-footprint]

### Update user reading footprint [POST]

Add user reading footprint data

+ Parameters
    + id: 123 (string) - The unique identifier of the user

+ Request with Body

    + Headers

            Content-Type: application/json
            Cookie: id_token=<id_token>
            Authorization: Bearer <jwt>

    + Attributes
        + post_id (string, required) - The post id of recording user reading footprint

+ Response 200 (application/json)

    + Attributes
        + status: success (string, required)

+ Response 201 (application/json)

    + Attributes
        + status: success (string, required)

+ Response 400

    + Attributes
        + status: fail (required)
        + message: Bad Request - The request body is missing required parameters or contains invalid data

+ Response 401

    + Attributes
        + status: error (required)
        + message: Unauthorized - The access token is invalid or has expired

+ Response 500

    + Attributes
        + status: error (required)
        + message: Internal Server Error - An error occurred while processing the request

## User Analytics Of Reading Footprint [/v2/users/{id}/analytics/reading-footprint{?limit,offset}]

### Get user reading footprint [GET]

Add user reading footprint data

+ Parameters
    + id: 123 (string) - The unique identifier of the user
    + offset: `0` (integer, optional) - The number of posts to skip
        + Default: `0`
    + limit: `10` (integer, optional) - The maximum number of posts to return
        + Default: `10`

+ Response 200 (application/json)

    + Attributes
        + status: success (required)
        + data
            + meta (meta, fixed-type, required)
            + records (array[UserReadingFootprint], fixed-type, required)

+ Response 500 (application/json)

    + Attributes
        + status: error (required)
        + message: Unexpected error. (required)

+ Response 504 (application/json)

    + Attributes
        + status: error (required)
        + message: Query upstream server timeout. (required)
