# Data Structures

## author
+ id: 5edf118c3e631f0600198935 (required)
+ job_title: 特約記者 (required)
+ name: 王大明 (required)

## category

+ id: 5edf118c3e631f0600198935 (required)
+ sort_order: 0 (number, required)
+ name: 文章類別 (required)

## image
+ id: 5edf118c3e631f0600198935 (required)
+ description: image description (required)
+ filetype: image/jpeg (required)
+ resized_targets (required)
    + mobile (resizeImage, required)
    + tiny (resizeImage, required)
    + desktop (resizeImage, required)
    + tablet (resizeImage, required)
    + w400 (resizeImage, required)

## tag
+ id: 5edf118c3e631f0600198935 (required)
+ name: tag name (required)

## paragraph
+ alignment: center (required)
+ content: context (array[string], required)
+ id: 1234 (required)
+ styles (object, required)
+ type: unstyled (required)

## paragraphs
+ api_data (array[paragraph], fixed-type)

## resizeImage
+ height: 600 (number, required)
+ width: 800 (number, required)
+ url: http://image.link (required)

## video
+ id: 5edf118c3e631f0600198935 (required)
+ title: video title (required)
+ filetype: video/mp4 (required)
+ size: 65536 (required)
+ url: http://video.url (required)

## meta
+ offset: 0 (number, required)
+ limit: 10 (number, required)
+ total: 100 (number, required)
