# Group Index Page

## Index Page [/v2/index_page]
A map contains consists mutiple post groups classified into following sections.

* LatestSection
* EditorPicksSection
* LatestTopicSection
* ReviewsSection
* TopicsSection
* PhotoSection
* InfographicSection
* HumanRightsAndSociety
* EnvironmentAndEducation
* PoliticsAndEconomy
* CultureAndArt
* International
* LivingAndMedicalCare
* World
* Humanrights
* PoliticsAndSociety
* Health
* Environment
* Econ
* Culture
* Education

## Get current index page [GET]

+ Response 200 (application/json)

    + Attributes
        + status: success (required)
        + data (IndexPage, required)

+ Response 204

+ Response 500 (application/json)

    + Attributes
        + status: error (required)
        + message: Unexpected error. (required)

+ Response 504 (application/json)

    + Attributes
        + status: error (required)
        + message: Query upstream server timeout. (required)

# Data Structures

## IndexPage
+ `latest_section` (array[MetaOfPost], fixed-type) - latest_section must contain exactly the latest 6 posts sorted by published_date
+ `editor_picks_section` (array[MetaOfPost], fixed-type) - editor_picks_section must contain exactly latest 6 posts sorted by updated_at
+ `latest_topic_section` (array[MetaOfTopic], fixed-type) - latest_topic_section must contain exactly latest 1 topic sorted by published_date
+ `reviews_section` (array[MetaOfPost], fixed-type) - reviews_section must contain exactly 4 posts sorted by published_date
+ `topics_section` (array[MetaOfTopic], fixed-type) - topics_section must contain exactly latest 4 topics (excluded latest one) sorted by published_date
+ `photos_section` (array[MetaOfPost], fixed-type) - photos_section must contain exactly 4 photo posts sorted by published_date 
+ `infographics_section` (array[MetaOfPost], fixed-type) - infographics_section must contain exactly 6 infographic posts sorted by published_date
+ `human_rights_and_society` (array[MetaOfPost], fixed-type) - human_rights_and_society must contain the latest post in human rights and society category sorted by published_date
+ `environment_and_education` (array[MetaOfPost], fixed-type) - environment_and_education must contain the latest post in environment and education category sorted by published_date
+ `politics_and_economy` (array[MetaOfPost], fixed-type) - politics_and_economy must contain the latest post in politics and economy category sorted by published_date
+ `culture_and_art` (array[MetaOfPost], fixed-type) - culture_and_art must contain the latest post in culture and art category sorted by published_date
+ `international` (array[MetaOfPost], fixed-type) - international must contain the latest post in international category sorted by published_date
+ `living_and_medical_care` (array[MetaOfPost], fixed-type) - living_and_medical_care must contain the latest post in living and medical care categroy sorted by published_date
+ `world` (array[MetaOfPost], fixed-type) - world must contain the latest post in world categroy sorted by published_date
+ `humanrights` (array[MetaOfPost], fixed-type) - humanrights must contain the latest post in humanrights categroy sorted by published_date
+ `politics_and_society` (array[MetaOfPost], fixed-type) - politics_and_society must contain the latest post in politics and society categroy sorted by published_date
+ `health` (array[MetaOfPost], fixed-type) - health must contain the latest post in health categroy sorted by published_date
+ `environment` (array[MetaOfPost], fixed-type) - environment must contain the latest post in environment categroy sorted by published_date
+ `econ` (array[MetaOfPost], fixed-type) - econ must contain the latest post in econ categroy sorted by published_date
+ `culture` (array[MetaOfPost], fixed-type) - culture must contain the latest post in culture categroy sorted by published_date
+ `education` (array[MetaOfPost], fixed-type) - education must contain the latest post in education categroy sorted by published_date
