## Data Structures

### PostReview
+ order: 2 (number, required) - The order of this review
+ post_id: 5edf118c3e631f0600198935 (string, required) - Unique id of the post
+ slug: `a-slug-of-the-post` (string, required) - Post slug
+ reviewWord: some review word (string) - The review word of the post
+ title: post title (string, required) - Post title
+ og_description: post description (string) - The og description of the post
+ og_image (image, required) - Post og images with rwd

# Group Post Reviews

## Review List [/v2/post_reviews]
A list contains information of the post reviews.

### Get post reviews [GET]

+ Request

    + Headers

            Content-Type: application/json
            Authorization: Bearer <jwt>

+ Response 200 (application/json)

    + Attributes
        + status: success (string, required) - The status of the API request (e.g. "success", "error")
        + data (array[PostReview], fixed-type, required)

+ Response 401

    + Attributes
        + status: error (required)
        + message: Unauthorized - The access token is invalid or has expired

+ Response 403

    + Attributes
        + status: error (required)
        + message: Forbbiden - The request is not permitted to reach the resource

+ Response 500

    + Attributes
        + status: error (required)
        + message: Unexpected error.
